# Generated by Django 5.1.1 on 2024-11-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_deck_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
