# Generated by Django 3.2.16 on 2025-02-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
