# Generated by Django 3.2.16 on 2024-11-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20241118_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-datetime_created',)},
        ),
        migrations.AddField(
            model_name='card',
            name='winrate',
            field=models.FloatField(default=None, verbose_name='Доля успеха'),
        ),
    ]
