# Generated by Django 3.2.16 on 2024-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20241119_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='winrate',
            field=models.FloatField(null=True, verbose_name='Доля успеха'),
        ),
    ]
