# Generated by Django 3.2.16 on 2024-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0005_alter_card_winrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='winrate',
            field=models.FloatField(default=0.0, verbose_name='Доля успеха'),
        ),
    ]
