# Generated by Django 3.2.16 on 2024-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0011_alter_card_winrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='card',
            name='datetime_reviewed',
            field=models.DateTimeField(default=None, verbose_name='Дата последнего ревью'),
        ),
    ]
