# Generated by Django 3.2.16 on 2025-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0014_alter_card_in_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Синоним'),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Синоним'),
        ),
    ]
