# Generated by Django 3.2.16 on 2024-11-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='deck',
            name='review_in_progress',
        ),
    ]
