# Generated by Django 3.2.16 on 2024-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0007_alter_card_winrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='winrate',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Доля успеха'),
        ),
    ]
