# Generated by Django 3.2.16 on 2024-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0012_auto_20241123_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='datetime_reviewed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего ревью'),
        ),
    ]
