# Generated by Django 3.2.16 on 2025-01-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0013_alter_card_datetime_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='in_queue',
            field=models.BooleanField(default=True, verbose_name='В очереди на ревью'),
        ),
    ]
