# Generated by Django 3.2.16 on 2025-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0015_auto_20250121_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Синоним (опционально)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Синоним (опционально)'),
        ),
    ]
